# https://github.com/probot/settings

branches:
    - name: master
      protection:
          enforce_admins: false
          required_pull_request_reviews:
              dismiss_stale_reviews: true
              require_code_owner_reviews: true
              required_approving_review_count: 1
          restrictions: null

labels:
    - name: bug
      color: ee0701

    - name: dependencies
      color: 0366d6

    - name: enhancement
      color: 0e8a16

    - name: question
      color: cc317c

    - name: security
      color: ee0701

    - name: stale
      color: eeeeee

repository:
    allow_merge_commit: true
    allow_rebase_merge: false
    allow_squash_merge: true
    default_branch: master
    description: "Container Implementation of PSR-11"
    homepage: https://jonathan.pt/blog/psr-11
    topics: psr-11,php,container,injection-container,php71,php72,php73,php74
    has_downloads: true
    has_issues: true
    has_pages: false
    has_projects: false
    has_wiki: false
    name: container
    private: false